name: Build Flutter Windows

on:
  push:
    tags:
      - 'v*'
    branches:
      - main

jobs:
  windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.35.6'

      - run: flutter config --enable-windows-desktop

      - run: flutter create .

      - run: flutter pub get

      - run: flutter build windows --release

      - name: List files to debug
        run: |
          dir build\windows\x64
          dir build\windows\x64\runner

      - uses: actions/upload-artifact@v4
        with:
          name: windows
          path: build\windows\x64\runner\Release

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: build\windows\x64\runner\Release\**\*.exe
          token: ${{ secrets.GITHUB_TOKEN }}