name: Build Flutter Windows

on:
  push:
    tags:
      - "v*"
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      # Checkout du code
      - name: Checkout code
        uses: actions/checkout@v4

      # Installation de Flutter
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.6"
          channel: "stable"

      # Configuration Windows
      - name: Enable Windows desktop support
        run: flutter config --enable-windows-desktop

      # Récupérer les dépendances
      - name: Get dependencies
        run: flutter pub get

      # Analyser le code
      - name: Analyze code
        run: flutter analyze

      # Builder l'exe
      - name: Build Windows app
        run: flutter build windows --release

      # Upload artifact
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: flutter-windows-build
          path: build/windows/runner/Release/

      # Créer une release (si c'est un tag)
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: build/windows/runner/Release/**/*
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Uploader l'exe uniquement
      - name: Upload EXE to Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: build/windows/runner/Release/gestion_web.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
